---
title: "Samples for the determination of total 25-hydroxyvitamin D levels were stable at ambient temperature"
author: "Ed Wilkes"
output:
  html_document:
    df_print: paged
---

# R setup
The following R packages and data are required for the analyses outlined in this notebook.
```{r setup, message=FALSE, warning=FALSE, echo=FALSE}
library(brms)
library(cowplot) 
library(ggdist)
library(tidyverse)
library(tidybayes)

plotTheme <- function(font_size, ...) {
  return(ggplot2::theme(
    panel.background = element_blank()
    ,panel.grid.minor = element_blank()
    ,panel.grid.major = element_blank()
    ,axis.text = element_text(size = font_size, colour = "black")
    ,axis.title = element_text(size = font_size, colour = "black")
    ,panel.border = element_rect(fill = NA, colour = "black")
    ,strip.background = element_rect(fill = "grey80", colour = "black")
    ,strip.text = element_text(size = font_size, colour = "black")
    ,legend.background = element_rect(fill = NA, colour = "black")
    ,legend.title = element_text(face = "bold", size = font_size, colour = "black")
    ,legend.text = element_text(size = font_size, colour = "black")
    ,...)
  )
}
```

# Data
```{r data, message=FALSE, warning=FALSE, echo=FALSE}
df_stability <- read.csv("~/WilkesEH_CCLM_stability_data.xlsx")
df_temp <- read.csv("~/WilkesEH_CCLM_temperature_data.xlsx")
df_time <- read.csv("~/WilkesEH_CCLM_transit_time_data.xlsx")
```

# Linear multilevel modelling
```{r model-fitting-stability, message=FALSE, warning=FALSE, echo=FALSE}
# DEQAS distributions 472 - 480 data
pooled_sd_stability <- round(sqrt((6.5^2 + 10.1^2 + 10.3^2 + 11.2^2 + 16.7^2 + 6.1^2 + 10.2^2 + 6.1^2 + 17.9^2) / 9), 2)
pooled_mean_stability <- round(mean(c(37.9, 69.2, 82.6, 78.6, 99.7, 42.8, 74.1, 30.8, 97.7)), 2) 
mad_concentration <- mad(df_stability$concentration, na.rm = TRUE)

# Variables to pass to brms/stan
stanvars <- brms::stanvar(pooled_sd_stability, "pooled_sd_stability")+
  brms::stanvar(pooled_mean_stability, "pooled_mean_stability")+
  brms::stanvar(mad_concentration, "mad_concentration")

# Fit Bayesian model
model_stability_slopes <- brms::brm(
  formula = bf(concentration ~ 0 + temperature + (0 + temperature|method) + (1|method/lab) + (1|sample))
  ,data = df_stability
  ,family = student
  ,prior = c(
     prior(normal(pooled_mean_stability, pooled_sd_stability * 10), class = "b", lb = 0)
    ,prior(gamma(2, 0.1), class = "nu")
    ,prior(student_t(3, 0, mad_concentration), class = "sd")
    ,prior(student_t(3, 0, mad_concentration), class = "sigma")
    ,prior(lkj(2), class = "L")
  )
  ,control = list(max_treedepth = 15, adapt_delta = 0.95)
  ,cores = 4
  ,iter = 4000
  ,seed = 1234
  ,stanvars = stanvars
)
```

```{r model-fitting-temp, message=FALSE, warning=FALSE, echo=FALSE}
# DEQAS distributions 586 - 590 data
pooled_sd_temp <- round(sqrt((4.3^2 + 7.1^2 + 8.9^2 + 6.1^2 + 6.2^2) / 5), 2)
pooled_mean_temp <- round(mean(c(39.0, 74.6, 95.6, 58.3, 58.7)))
mad_concentration_temp <- round(mad(df_temp$concentration, na.rm = TRUE), 2)

# Variables to pass to brms/stan
stanvars <- brms::stanvar(pooled_sd_temp, "pooled_sd_temp")+
  brms::stanvar(pooled_mean_temp, "pooled_mean_temp")+
  brms::stanvar(mad_concentration_temp, "mad_concentration_temp")

# Fit Bayesian model
model_temp_slopes <- brm(
  bf(concentration ~ 0 + temperature + (0 + temperature|method) + (1|method/lab))
  ,data = df_temp
  ,family = student
  ,cores = 4
  ,iter = 4000
  ,prior = c(
    prior(normal(pooled_mean_temp, pooled_sd_temp * 10), class = "b", lb = 0)
    ,prior(gamma(2, 0.1), class = "nu")
    ,prior(student_t(3, 0, mad_concentration_temp), class = "sd")
    ,prior(student_t(3, 0, mad_concentration_temp), class = "sigma")
    ,prior(lkj(2), class = "L")
  )
  ,control = list(max_treedepth = 15, adapt_delta = 0.95)
  ,seed = 1234
  ,stanvar = stanvars
)
```

# Figures
```{r figure-functions, message=FALSE, warning=FALSE, echo=FALSE}
getPosteriors <- function(model, pars, contrast) {
  
  as_draws_df(model) |>
    select(.chain, .iteration, all_of(pars)) |>
    mutate(contrast = !!rlang::parse_expr(contrast)) |>
    pivot_longer(-c(.chain, .iteration), names_to = "parameter") |>
    group_by(parameter) |>
    mutate(lwr = quantile(value, 0.025), upr = quantile(value, 0.975)) |>
    summarise(
      dens_x = density(value, adjust = 2)$x
      ,dens_y = density(value, adjust = 2)$y
      ,lwr = mean(lwr)
      ,upr = mean(upr)
    ) |>
    mutate(within_interval = if_else(dens_x >= lwr & dens_x <= upr, "yes", "no"))
  
}

plotPosteriors <- function(data, model, par, size = 0.5, xlim, break_width, colours) {
  
  ggplot(data|>filter(parameter == par), aes(x = dens_x, y = dens_y))+
    geom_area(colour = "black", fill = colours[1], size = size, alpha = 0.25)+
    geom_area(
      data = filter(data, within_interval == "yes", parameter == par)
      ,fill = colours[2]
      ,alpha = 0.5
    )+
    geom_vline(
      colour = "red2"
      ,linetype = "dashed"
      ,xintercept = median(as.matrix(model)[,par])
    )+
    plotTheme(12)+
    xlab("Total 25-hydroxyvitamin D (nmol/L)")+
    ylab("Normalised density (A.U.)")+
    scale_x_continuous(limits = xlim, breaks = seq(xlim[1], xlim[2], break_width))
  
}

plotContrast <- function(data, model, pars, xlim, break_width) {
  
  ggplot(data|>filter(parameter == "contrast"), aes(x = dens_x, y = dens_y))+
    geom_area(colour = "black", fill = "grey70", size = size, alpha = 0.25)+
    geom_area(
      data = filter(data, within_interval == "yes", parameter == "contrast")
      ,fill = "grey60"
      ,alpha = 0.5
    )+
    geom_vline(
      colour = "red2"
      ,linetype = "dashed"
      ,size = size
      ,xintercept = median(as.matrix(model)[,pars[1]] - as.matrix(model)[,pars[2]])
    )+
    geom_vline(xintercept = 0)+
    plotTheme(12)+
    xlab("Total 25-hydroxyvitamin D (nmol/L)")+
    ylab("Normalised density (A.U.)")+
    scale_x_continuous(limits = c(xlim[1], xlim[2]), breaks = seq(xlim[1], xlim[2], break_width))
  
}

plotMCMC <- function(model, pars) {
  
  posterior_samples <- brms::as_draws_df(model) |>
    dplyr::select(all_of(pars), .chain, .iteration) |>
    tidyr::pivot_longer(cols = -c(.iteration, .chain), names_to = "parameter")
  
  binwidth <- max(posterior_samples$.iteration) * 0.02

  traces <- posterior_samples |>
    ggplot2::ggplot(aes(x = .iteration, y = value))+
    ggplot2::geom_step(aes(colour = as.factor(.chain)), alpha = 0.5, stat = "summary_bin", binwidth = binwidth, fun = "median", size = 0.5)+
    ggplot2::facet_wrap(~parameter, ncol = 2, scale = "free")+
    ggplot2::xlab("Iteration")+
    ggplot2::ylab("Parameter value")+
    ggplot2::labs(colour = "Chain")+
    ggplot2::scale_colour_manual(values = paste0("dodgerblue", 1:4))+
    plotTheme(12)
  
  return(traces)
  
}
```

```{r figure-1, message=FALSE, warning=FALSE, echo=FALSE}
fig1 <- df_stability |> 
  remove_missing() |> 
  ggplot(aes(x = as.numeric(sample), y = concentration, fill = temperature, colour = temperature))+
    geom_vline(xintercept = 1.5, alpha = 0.25, size = 0.25)+
    geom_vline(xintercept = 2.5, alpha = 0.25, size = 0.25)+
    geom_vline(xintercept = 3.5, alpha = 0.25, size = 0.25)+
    geom_vline(xintercept = 4.5, alpha = 0.25, size = 0.25)+
    geom_vline(xintercept = 5.5, alpha = 0.25, size = 0.25)+
    geom_vline(xintercept = 6.5, alpha = 0.25, size = 0.25)+
    geom_vline(xintercept = 7.5, alpha = 0.25, size = 0.25)+
    geom_vline(xintercept = 8.5, alpha = 0.25, size = 0.25)+
    geom_point(alpha = 0.5, position = position_dodge(width = 0.75))+
    plotTheme(12)+
    theme(
        strip.text = element_text(size = 8)
        ,legend.position = "bottom"
    )+
    expand_limits(y = 0)+
    scale_fill_manual(values = c("deepskyblue", "darkorange"))+
    scale_colour_manual(values = c("deepskyblue", "darkorange"))+
    labs(fill = "Shipping temperature", colour = "Shipping temperature")+
    xlab("Sample number")+
    ylab("Total 25-hydroxyvitamin D (nmol/L)")+
    facet_wrap(~method, ncol = 3)+
    scale_x_continuous(breaks = 1:9)
```

```{r figure-2, message=FALSE, warning=FALSE, echo=FALSE}
post_stability <- getPosteriors(
  model_stability_slopes
  ,pars = c("b_temperatureFrozen", "b_temperatureAmbient")
  ,contrast = c("b_temperatureAmbient - b_temperatureFrozen")
)

fig2a <- plotPosteriors(
  data = post_stability
  ,model = model_stability_slopes
  ,par = "b_temperatureFrozen"
  ,size = 0.5
  ,xlim = c(0, 140)
  ,break_width = 20
  ,colours = c("deepskyblue", "deepskyblue3")
)
  
fig2b <- plotPosteriors(
  data = post_stability
  ,model = model_stability_slopes
  ,par = "b_temperatureAmbient"
  ,size = 0.5
  ,xlim = c(0, 140)
  ,break_width = 20
  ,colours = c("darkorange", "darkorange3")
)

fig2c <- plotContrast(
  data = post_stability
  ,model = model_stability_slopes
  ,pars = c("b_temperatureAmbient", "b_temperatureFrozen")
  ,xlim = c(-10, 10)
  ,break_width = 2
)

fig2 <- cowplot::plot_grid(fig2a, fig2b, fig2c, labels = "AUTO", align = "hv")
```

```{r figure-3, message=FALSE, warning=FALSE, echo=FALSE}
df_temp_na <- remove_missing(df_temp)
df_pred <- as.data.frame(t(posterior_predict(model_temp_slopes))) |>
  mutate(
    temperature = df_temp_na$temperature
    ,method = df_temp_na$method
    ,lab = df_temp_na$lab
  ) |>
  pivot_longer(cols = -c(temperature, method, lab), names_to = "sample", values_to = "result")

fig3 <- ggplot(df_temp, aes(x = temperature, y = concentration, colour = temperature))+
  geom_line(aes(group = lab), colour = "grey80", alpha = 0.5)+
  geom_point(alpha = 0.5)+
  facet_wrap(~method)+
  plotTheme(12)+
  theme(
    legend.position = "none"
    ,strip.text = element_text(colour = "black", size = 10)
    ,axis.text.x = element_text(colour = "black", angle = 90, hjust = 1, vjust = 0.5)
  )+
  labs(colour = "Storage temperature")+
  scale_colour_manual(values = c("deepskyblue", "darkorange"))+
  xlab("")+
  ylab("Total 25-hydroxyvitamin D (nmol/L)")+
  expand_limits(y = 0)
```

```{r figure-4, message=FALSE, warning=FALSE, echo=FALSE}
post_temp <- getPosteriors(
  model_temp_slopes
  ,pars = c("b_temperatureFrozen", "b_temperatureRoom")
  ,contrast = c("b_temperatureRoom - b_temperatureFrozen")
)

fig4a <- plotPosteriors(
  data = post_temp
  ,model = model_temp_slopes
  ,par = "b_temperatureFrozen"
  ,size = 0.5
  ,xlim = c(55, 65)
  ,break_width = 2.5
  ,colours = c("deepskyblue", "deepskyblue3")
)

fig4b <- plotPosteriors(
  data = post_temp
  ,model = model_temp_slopes
  ,par = "b_temperatureRoom"
  ,size = 0.5
  ,xlim = c(55, 65)
  ,break_width = 2.5
  ,colours = c("darkorange", "darkorange3")
)

fig4c <- plotContrast(
  data = post_temp
  ,model = model_temp_slopes
  ,pars = c("b_temperatureRoom", "b_temperatureFrozen")
  ,xlim = c(-4, 4)
  ,break_width = 2
)

fig4 <- cowplot::plot_grid(fig4a, fig4b, fig4c, labels = "AUTO", align = "hv")
```

```{r figure-5, message=FALSE, warning=FALSE, echo=FALSE}
df_time_sum <- df_time |>
  group_by(sample) |>
  summarise(mean_concentration = mean(concentration, na.rm = T))

top_methods <- c("DiaSorin Liaison Total", "LC-MS-MS", "Roche Total 25OHD", "Abbott Architect - New (5P02)", "Roche Vitamin D Total II")

fig5 <- ggplot(filter(df_time, method %in% top_methods),aes(y = concentration, x = transit_time))+
  geom_point(alpha = 0.25)+
  geom_hline(data = df_time_sum, aes(yintercept = mean_concentration), linetype = "dashed", colour = "red2")+
  facet_wrap(~method+sample, ncol = 5)+
  plotTheme(12)+
  xlab("Transit time (days)")+
  ylab("Total 25-hydroxyvitamin D (nmol/L)")
```

# Supplemental
```{r figure-s1, message=FALSE, warning=FALSE, echo=FALSE}
# Prior distributions
df_priors_stability <- list(
  alpha = data.frame(parameter = "alpha", x = 0:400, dens = dnorm(0:400, pooled_mean_stability, pooled_sd_stability * 10))
  ,nu = data.frame(parameter = "nu", x = 0:150, dens = dgamma(0:150, 2, 0.1))
  ,sigma = data.frame(parameter = "sigma", x = 0:200, dens = dstudent_t(seq(0,200), 3, 0, mad_concentration))
  ,cor = data.frame(parameter = "cor", x = seq(-1,1,0.01), dens = dlkjcorr_marginal(seq(-1,1,0.01), K = 2, eta = 2))
) |>
  bind_rows() 

figS1a <- ggplot(df_priors_stability |> filter(parameter == "nu"), aes(x = x, y = dens))+
  geom_line(colour = "red2", size = 1)+
  plotTheme(12)+
  facet_wrap(~parameter, scale = "free", ncol = 2)+
  xlab("Degrees of freedom (n)")+
  ylab("Density (A.U.)")

figS1b <- ggplot(df_priors_stability |> filter(parameter == "alpha"), aes(x = x, y = dens))+
  geom_line(colour = "red2", size = 1)+
  plotTheme(12)+
  facet_wrap(~parameter, scale = "free", ncol = 2)+
  xlab("Total 25-hydroxyvitamin D (nmol/L)")+
  ylab("Density (A.U.)")

figS1c <- ggplot(df_priors_stability |> filter(parameter == "cor"), aes(x = x, y = dens))+
  geom_line(colour = "red2", size = 1)+
  plotTheme(12)+
  facet_wrap(~parameter, scale = "free", ncol = 2)+
  xlab("Correlation (A.U.)")+
  ylab("Density (A.U.)")

figS1d <- ggplot(df_priors_stability |> filter(parameter == "sigma"), aes(x = x, y = dens))+
  geom_line(colour = "red2", size = 1)+
  plotTheme(12)+
  facet_wrap(~parameter, scale = "free", ncol = 2)+
  xlab("Total 25-hydroxyvitamin D (nmol/L)")+
  ylab("Density (A.U.)")

figS1 <- cowplot::plot_grid(figS1a, figS1b, figS1c, figS1d, labels = "AUTO", ncol = 2, align = "hv")
```

```{r figure-s2, message=FALSE, warning=FALSE, echo=FALSE}
# Prior distributions
df_priors_temp <- list(
  alpha = data.frame(parameter = "alpha", x = 0:200, dens = dnorm(0:200, pooled_mean_temp, pooled_sd_temp * 10))
  ,sigma = data.frame(parameter = "sigma", x = 0:50, dens = dstudent_t(seq(0,50), 3, 0, mad_concentration_temp))
) |>
  bind_rows() 

figS2a <- ggplot(df_priors_temp |> filter(parameter == "alpha"), aes(x = x, y = dens))+
  geom_line(colour = "red2", size = 1)+
  plotTheme(12)+
  facet_wrap(~parameter, scale = "free", ncol = 2)+
  xlab("Total 25-hydroxyvitamin D (nmol/L)")+
  ylab("Density (A.U.)")

figS2b <- ggplot(df_priors_temp |> filter(parameter == "sigma"), aes(x = x, y = dens))+
  geom_line(colour = "red2", size = 1)+
  plotTheme(12)+
  facet_wrap(~parameter, scale = "free", ncol = 2)+
  xlab("Total 25-hydroxyvitamin D (nmol/L)")+
  ylab("Density (A.U.)")

figS2 <- cowplot::plot_grid(figS2a, figS2b, labels = "AUTO", ncol = 2, align = "hv")
```

```{r figure-s3, message=FALSE, warning=FALSE, echo=FALSE}
# Posterior predictive checks
df_stability_na <- remove_missing(df_stability)
df_pred_stability <- as.data.frame(t(posterior_predict(model_stability_slopes, cores = 4))) |>
  mutate(
    temperature = df_stability_na$temperature
    ,method = df_stability_na$method
    ,lab = df_stability_na$lab
    ,sample = df_stability_na$sample
  ) |>
  pivot_longer(cols = -c(temperature, method, lab, sample), names_to = "prediction", values_to = "result") |>
  group_by(temperature, method, lab, sample) |>
  summarise(median_prediction = median(result, na.rm = TRUE)) |>
  left_join(df_stability, by = c("temperature", "lab", "sample"))

figS3 <- ggplot(df_pred_stability, aes(x = median_prediction, y = concentration, colour = sample))+
  geom_abline(slope = 1, intercept = 0, linetype = "dashed")+
  geom_point(alpha = 0.5)+
  facet_wrap(~lab)+
  plotTheme(12)+
  xlab("Median predicted total 25-hydroxyvitamin D (nmol/L)")+
  ylab("Measured total 25-hydroxyvitamin D (nmol/L)")+
  xlim(c(0, 160))+
  ylim(c(0, 160))+
  labs(colour = "Sample")
```

```{r figure-s4, message=FALSE, warning=FALSE, echo=FALSE}
# MCMC diagnostics
figS4 <- plotMCMC(model_stability_slopes, pars = 1:10)
```

```{r figure-s5, message=FALSE, warning=FALSE, echo=FALSE}
# Varying slope posterior distributions
figS5 <- model_stability_slopes |>
  spread_draws(b_temperatureFrozen, b_temperatureAmbient, r_method[method,coefficient]) |>
  pivot_wider(
    id_cols = c(.chain, .iteration, .draw, b_temperatureFrozen, b_temperatureAmbient, method)
    ,names_from = coefficient
    ,values_from = r_method
  ) |>
  mutate(
    frozen = b_temperatureFrozen + Intercept + temperatureFrozen # method-level effect
    ,ambient = b_temperatureAmbient + Intercept + temperatureAmbient # method-level effect
  ) |>
  select(.iteration, method, frozen, ambient) |>
  pivot_longer(cols = -c(.iteration, method), names_to = "temperature", values_to = "value") |>
  mutate(temperature = factor(temperature, levels = c("frozen", "ambient"))) |>
  ggplot(aes(x = temperature, y = value, colour = temperature))+
  ggdist::stat_halfeye(adjust = 2, aes(fill = temperature), alpha = 0.5, normalize = "groups")+
  scale_colour_manual(values = c("deepskyblue", "darkorange"))+
  scale_fill_manual(values = c("deepskyblue", "darkorange"))+
  facet_wrap(~method, ncol = 3)+
  plotTheme(font_size = 12, legend.position = "none")+
  xlab("Shipping temperature")+
  ylab("Total 25-hydroxyvitamin D (nmol/L)")+
  expand_limits(y = 0)
```

```{r figure-s6, message=FALSE, warning=FALSE, echo=FALSE}
# Posterior predictive checks
df_temp_na <- remove_missing(df_temp)
df_pred_temp <- as.data.frame(t(posterior_predict(model_temp_slopes, cores = 4))) |>
  mutate(
    temperature = df_temp_na$temperature
    ,method = df_temp_na$method
    ,lab = df_temp_na$lab
    ,sample = df_temp_na$sample
  ) |>
  pivot_longer(cols = -c(temperature, method, lab, sample), names_to = "prediction", values_to = "result") |>
  group_by(temperature, method, lab, sample) |>
  summarise(median_prediction = median(result, na.rm = TRUE)) |>
  left_join(df_temp, by = c("temperature", "lab", "sample", "method"))

figS6 <- ggplot(df_pred_temp, aes(x = median_prediction, y = concentration, colour = sample))+
  geom_abline(slope = 1, intercept = 0, linetype = "dashed")+
  geom_point(alpha = 0.5)+
  facet_wrap(~method, ncol = 5)+
  plotTheme(12)+
  xlab("Median predicted total 25-hydroxyvitamin D (nmol/L)")+
  ylab("Measured total 25-hydroxyvitamin D (nmol/L)")+
  xlim(c(0, 100))+
  ylim(c(0, 100))+
  labs(colour = "Sample")
```

```{r figure-s7, message=FALSE, warning=FALSE, echo=FALSE}
# MCMC diagnostics
figS7 <- plotMCMC(model_temp_slopes, pars = 1:9)
```

```{r figure-s8, message=FALSE, warning=FALSE, echo=FALSE}
# Varying slope posterior distributions
figS8 <- model_temp_slopes |>
  spread_draws(b_temperatureFrozen, b_temperatureRoom, r_method[method,coefficient]) |>
  pivot_wider(
    id_cols = c(.chain, .iteration, .draw, b_temperatureFrozen, b_temperatureRoom, method)
    ,names_from = coefficient
    ,values_from = r_method
  ) |>
  mutate(
    frozen = b_temperatureFrozen + Intercept + temperatureFrozen # method-level effect
    ,room = b_temperatureRoom + Intercept + temperatureRoom # method-level effect
  ) |>
  select(.iteration, method, frozen, room) |>
  pivot_longer(cols = -c(.iteration, method), names_to = "temperature", values_to = "value") |>
  mutate(temperature = factor(temperature, levels = c("frozen", "room"))) |>
  ggplot(aes(x = temperature, y = value, colour = temperature))+
  ggdist::stat_halfeye(adjust = 2, aes(fill = temperature), alpha = 0.5, .width = c(0.68, 0.95), normalize = "groups")+
  scale_colour_manual(values = c("deepskyblue", "darkorange"))+
  scale_fill_manual(values = c("deepskyblue", "darkorange"))+
  facet_wrap(~method, ncol = 5)+
  plotTheme(font_size = 12, legend.position = "none")+
  expand_limits(y = 0)+
  xlab("Storage temperature")+
  ylab("Total 25-hydroxyvitamin D (nmol/L)")
```

```{r figure-s9, message=FALSE, warning=FALSE, echo=FALSE}
figS9 <- ggplot(df_time, aes(y = concentration, x = transit_time))+
  geom_point(alpha = 0.25)+
  geom_hline(data = df_time_sum, aes(yintercept = mean_concentration), linetype = "dashed", colour = "red2")+
  facet_wrap(~sample, ncol = 2)+
  plotTheme(12)+
  xlab("Transit time (days)")+
  ylab("Total 25-hydroxyvitamin D (nmol/L)")
```