---
title: "Supplementary material: A practical guide to Bayesian statistics in laboratory medicine"
author: "Wilkes EH"
output: 
  bookdown::pdf_document2
---

# Code snippet 1
```{r load-packages, message=FALSE, warning=FALSE}
# Loading the required packages
library(bayesplot) # v1.8.0
library(brms) # v2.15.0
# cowplot v1.1.1 (not loaded directly to avoid overwriting ggplot2 themes)
library(dplyr) # v1.0.7
library(ggplot2) # v3.3.5
library(mcr) # v1.2.2
library(rstanarm) # v2.21.1
library(tidybayes) # v2.3.1
library(tidyr) # v1.1.4
library(VCA) # v1.4.3

# A convenience function for altering the aesthetics plots 
theme_plot <- theme(
  panel.background = element_blank()
  ,panel.border = element_rect(fill = NA, colour = "black")
  ,panel.grid.major = element_blank()
  ,panel.grid.minor = element_blank()
  ,axis.title = element_text(colour = "black", size = 12, family = "sans")
  ,axis.text = element_text(colour = "black", size = 12, family = "sans")
  ,axis.ticks = element_line(colour = "black")
  ,legend.text =  element_text(colour = "black", family = "sans")
  ,legend.title = element_text(colour = "black", family = "sans")
  ,legend.background = element_rect(colour = "black", fill = "white")
  ,strip.text = element_text(colour = "black", family = "sans")
)
```

# Code snippet 2
```{r snippet-2, warning=FALSE, message=FALSE}
# Set the random seed for reproducibility
set.seed(1234)

# Generate simulated data
df_example_1 <- data.frame(
  treatment = rep(c("Control", "Drug"), each = 20)
  ,calcium = c(
    rnorm(n = 20, mean = 2.9, sd = 0.2)
    ,rnorm(n = 20, mean = 2.6, sd = 0.2)
  )
)

# Perform a t test
t.test(calcium ~ treatment, data = df_example_1, paired = FALSE, var.equal = TRUE)
```

# Code snippet 3
```{r snippet-3, warning=FALSE, message=FALSE}
# Fit a Bayesian model with brms
model_1 <- brm(
  formula = calcium ~ 1 + treatment
  ,data = df_example_1
  ,prior = c(
    prior(normal(2.4, 1), class = "Intercept") # prior on beta_0
    ,prior(normal(0, 1), class = "b") # prior on beta_1
    ,prior(exponential(6.2), class = "sigma") # prior on sigma
  )
  ,seed = 1234 # for reproducibility
  ,refresh = 0 # suppress messages for clarity
)
```

# Code snippet 4
```{r snippet-4, warning=FALSE, message=FALSE}
# Call the model summary
model_1

# Calculate the number of posterior samples that are < 0
sum_g_zero <- sum(as.matrix(model_1)[,"b_treatmentDrug"] < 0) 

# Divide this value by the total number of posterior samples
sum_g_zero / length(as.matrix(model_1)[,"b_treatmentDrug"]) * 100
```

# Code snippet 5
```{r snippet-5, warning=FALSE, message=FALSE}
# Set the random seed for reproducibility
set.seed(1234)

# Generate simulated data
df_example_2 <- data.frame(
  treatment = rep(c("Control", "Drug"), each = 20)
  ,calcium = c(
    rnorm(n = 20, mean = 2.9, sd = 0.4)
    ,rnorm(n = 20, mean = 2.6, sd = 0.2)
  )
)

# Perform a Welch's t test
t.test(calcium ~ treatment, data = df_example_2, paired = FALSE, var.equal = FALSE)
```

# Figure 1
```{r fig-1, echo=FALSE, warning=FALSE, message=FALSE}
# Figure 1A
fig_1a <- ggplot(df_example_1, aes(x = treatment, y = calcium))+
  geom_jitter(width = 0.01, alpha = 0.5)+
  theme_plot+
  xlab("")+
  ylab("Total calcium (mmol/L)")

# Figure 1B
fig_1b <- ggplot(data.frame(x = c(-10, 10)), aes(x = x))+
  stat_function(fun = dt, geom = "line", args = list(df = 38))+
  geom_vline(xintercept = t.test(calcium ~ treatment, data = df_example_1, paired = FALSE, var.equal = TRUE)$statistic, colour = "red2")+
  theme_plot+
  xlab("t")+
  ylab("Density (A.U.)")

# Figure 1C
fig_1c <- pp_check(model_1, type = "stat_grouped", group = "treatment")+
  xlab("Total calcium (mmol/L)")+
  ylab("Density (A.U.)")+
  theme_plot+
  theme(legend.position = "none", strip.background = element_rect(fill = "grey80"))

# Figure 1D
fig_1d <- mcmc_areas(
  model_1
  ,pars = "b_Intercept" # the parameter to plot
  ,adjust = 1.5 # smooth the densities slightly
  ,prob = 0.95 # shade the 95% credible intervals
)+
  geom_vline(xintercept = 2.9, col = "red2")+
  xlab(expression(paste("Total calcium in group 1 (", beta[0], ", mmol/L)")))+
  ylab("Density (A.U.)")+
  theme_plot+
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())

# Figure 1E
fig_1e <- mcmc_areas(
  model_1
  ,pars = "b_treatmentDrug"
  ,adjust = 1.5 # smooth the densities slightly
  ,prob = 0.95 # shade the 95% credible intervals
)+
  geom_vline(xintercept = -0.3, col = "red2")+
  xlab(expression(paste("Difference in total calcium (", beta[1], ", mmol/L)")))+
  ylab("Density (A.U.)")+
  theme_plot+
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())

# Figure 1F
t_val <- t.test(calcium ~ treatment, data = df_example_2, paired = FALSE, var.equal = FALSE)$statistic
fig_1f <- ggplot(data.frame(x = c(-10, 10)), aes(x = x))+
  stat_function(fun = dt, geom = "line", args = list(df = 38))+
  geom_vline(xintercept = t_val, colour = "red2")+
  stat_function(fun = dt, geom = "area", args = list(df = 38), xlim = c(t_val, 10), fill = "red2", alpha = 0.5)+
  theme_plot+
  xlab("t")+
  ylab("Density (A.U.)")

# Combine panels
cowplot::plot_grid(fig_1a, fig_1b, fig_1c, fig_1d, fig_1e, fig_1f, align = "hv", axis = "lb", labels = c("A", "B", "C", "D", "E", "F"), ncol = 3)
```

# Figure S1
```{r fig-s1, echo=FALSE, warning=FALSE, message=FALSE}
# Beta_0
fig_s1a <- ggplot(data.frame(x = c(-1.6, 6.4)), aes(x = x))+
  stat_function(fun = dnorm, geom = "line", args = list(mean = 2.4, sd = 1))+
  theme_plot+
  xlab(expression(paste("Intercept value (", beta[0], ", mmol/L)")))+
  ylab("Density (A.U.)")

# Beta_1
fig_s1b <- ggplot(data.frame(x = c(-4, 4)), aes(x = x))+
  stat_function(fun = dnorm, geom = "line", args = list(mean = 0, sd = 1))+
  theme_plot+
  xlab(expression(paste("Slope value (", beta[1], ", mmol/L)")))+
  ylab("Density (A.U.)")

# Sigma
fig_s1c <- ggplot(data.frame(x = c(0, 1.5)), aes(x = x))+
  stat_function(fun = dexp, geom = "line", args = list(rate = 6.2))+
  theme_plot+
  xlab(expression(paste("Intercept value (", sigma, ", mmol/L)")))+
  ylab("Density (A.U.)")

cowplot::plot_grid(fig_s1a, fig_s1b, fig_s1c, labels = c("A", "B", "C"), align = "hv", label_size = 16)
```

# Figure S2
```{r fig-s2, echo=FALSE, warning=FALSE, message=FALSE}
# Visualise the MCMC traces
fig_s2 <- mcmc_trace(
  model_1 # our model
  ,pars = c("b_Intercept", "b_treatmentDrug", "sigma") # the parameters to plot
  ,facet_args = list(ncol = 2) # some graphical display options
)+
  xlab("Simulation number")+
  ylab("Parameter value")+
  theme_plot+
  theme(strip.background = element_rect(fill = "grey80"))
```

# Code snippet 6
```{r snippet-6, warning=FALSE, message=FALSE}
# Fit a Bayesian model with brms
model_2 <- brm(
  formula = bf(calcium ~ 1 + treatment, sigma ~ treatment)
  ,data = df_example_2
  ,prior = c(
    prior(normal(2.4, 1), class = "Intercept") # prior on beta_0
    ,prior(normal(0, 1), class = "b", coef = "treatmentDrug") # prior on beta_1
    ,prior(normal(0, 5), class = "Intercept", dpar = "sigma") # prior on gamma_0
    ,prior(normal(0, 5), class = "b", dpar = "sigma") # prior on gamma_1
  )
  ,seed = 1234 # for reproducibility
  ,refresh = 0 # suppress messages for clarity
)

# Examine the model's estimates
model_2

# Calculate the SD for group 1 (note the back-transformation from the log scale)
quantile(exp(as.matrix(model_2)[,"b_sigma_Intercept"]), probs = c(0.025, 0.5, 0.975)) 

# Calculate the SD for group 2
quantile(
  exp(as.matrix(model_2)[,"b_sigma_Intercept"] + as.matrix(model_2)[,"b_sigma_treatmentDrug"])
  ,probs = c(0.025, 0.5, 0.975)
)
```

# Code snippet 7
```{r, snippet-7, warning=FALSE, message=FALSE}
# Set the random seed for reproducibility
set.seed(1234)

# Generate some dummy data
df_example_3 <- data.frame(
  group = rep(c("Control", "Treatment"), each = 50)
  ,outcome = c(
    rbinom(n = 50, size = 1, prob = 0.25) # where 1 represents an MI event
    ,rbinom(n = 50, size = 1, prob = 0.10)
  )
)

# Summarise the data
table(df_example_3$group, df_example_3$outcome)

# Perform a chi-squared test
chisq.test(x = df_example_3$group, y = df_example_3$outcome)
```

# Code snippet 8
```{r snippet-8, warning=FALSE, message=FALSE}
# Fit a Bayesian model with brms
model_3 <- brm(
  formula = outcome | trials(1) ~ 1 + group
  ,data = df_example_3
  ,family = binomial # using the binomial likelihood
  ,prior = c(
    prior(normal(0, 10), class = "Intercept") # prior on beta_0
    ,prior(normal(0, 2.5), class = "b") # prior on beta_1
  )
  ,seed = 1234
  ,refresh = 0
)

# Examine the model's results
model_3

# Calculate the rate of MI events for group 1 (control)
# Note that we are required to transform to get back to the probability scale from the log odds
quantile(plogis(as.matrix(model_3)[,"b_Intercept"]), probs = c(0.025, 0.5, 0.975))

# Calculate the rate of MI events for group 2 (treatment)
quantile(
  plogis(as.matrix(model_3)[,"b_Intercept"] + as.matrix(model_3)[,"b_groupTreatment"])
  ,probs = c(0.025, 0.5, 0.975)
)

# Calculate the probability that the rates are different between treatment and control
difference <- (plogis(as.matrix(model_3)[,"b_Intercept"] + as.matrix(model_3)[,"b_groupTreatment"])) - 
  plogis(as.matrix(model_3)[,"b_Intercept"]) 
  
sum(difference < 0) / length(as.matrix(model_3)[,"b_Intercept"])
```

# Figure 2
```{r fig-2, message=FALSE, warning=FALSE}
df_densities <- data.frame(value = difference) %>%
  mutate(lwr = quantile(value, 0.025), upr = quantile(value, 0.975)) %>%
  summarise(
    density_x = density(value, adjust = 1.5)$x
    ,density_y = density(value, adjust = 1.5)$y
    ,lwr = mean(lwr)
    ,upr = mean(upr)
    ,max_density = max(density_y, na.rm = TRUE)
    ,density_y_norm = density_y / max_density
  ) %>%
  rowwise() %>%
  mutate(density_x_95 = if_else(density_x > lwr & density_x < upr, true = density_x, false = NULL))  

fig_2 <- ggplot(df_densities, aes(x = density_x, y = density_y_norm))+
  geom_line()+
  geom_area(aes(x = density_x_95), fill = "dodgerblue2", alpha = 0.25, colour = "black")+
  geom_vline(xintercept = 0, colour = "black")+
  geom_vline(xintercept = median(difference), colour = "dodgerblue4", size = 1)+
  theme_plot+
  xlab(expression(paste("Difference in MI rates (Treatment [", theta[2], "] - Control [", theta[1], "])")))+
  ylab("Density (A.U.)")+
  xlim(c(-0.5, 0.5))
```

# Figure S3
```{r fig-s3, echo=FALSE, warning=FALSE, message=FALSE}
# Beta_0
fig_s3a <- ggplot(data.frame(x = c(-40, 40)), aes(x = x))+
  stat_function(fun = dnorm, geom = "line", args = list(mean = 0, sd = 10))+
  theme_plot+
  xlab(expression(paste("Intercept value (", beta[0], ", mmol/L)")))+
  ylab("Density (A.U.)")

# Beta_1
fig_s3b <- ggplot(data.frame(x = c(-10, 10)), aes(x = x))+
  stat_function(fun = dnorm, geom = "line", args = list(mean = 0, sd = 1))+
  theme_plot+
  xlab(expression(paste("Slope value (", beta[1], ", mmol/L)")))+
  ylab("Density (A.U.)")

cowplot::plot_grid(fig_s3a, fig_s3b, labels = c("A", "B"), align = "hv", label_size = 16)
```
# Code snippet 9
```{r snippet-9, warning=FALSE, message=FALSE}
# Set the random seed for reproducibility
set.seed(1234)

# Generate some dummy potassium data
df_example_4 <- data.frame(analyser_1 = rnorm(20, mean = 4.5, sd = 0.75)) %>%
  mutate(
    # Generate data with a 2 mmol/L positive constant bias and a slope of 1
    analyser_2 = analyser_1 * 1 + rnorm(20, 1, sd = 0.05) 
    
    # Add measurement error to x (CV of 3%)
    ,analyser_1 = analyser_1 + rnorm(20, mean = 0, 0.03 * analyser_1) 
    
    # Add measurement error to y (CV of 3%)
    ,analyser_2 = analyser_2 + rnorm(20, mean = 0, 0.03 * analyser_2) 
    
    # Back-calculate the relevant SDs
    ,sd_analyser_1 = analyser_1 * 0.03
    ,sd_analyser_2 = analyser_2 * 0.03
  )

# Fit a Passing-Bablok regression model
mcr_model <- mcreg(x = df_example_4$analyser_1, y = df_example_4$analyser_2, method.reg = "PaBa")
mcr_model@para
```

# Code snippet 10
```{r snippet-10, warning=FALSE, message=FALSE}
model_4 <- brm(
  formula = analyser_2 ~ 0 + Intercept + analyser_1
  ,data = df_example_4
  ,family = gaussian
  ,prior = c(
    prior(student_t(3, 0, 2.5), class = "b", coef = "Intercept") # prior on beta_0
    ,prior(normal(1, 0.5), class = "b", coef = "analyser_1") # prior on beta_1
    ,prior(exponential(1.7), class = "sigma")
  )
  ,seed = 1234
  ,refresh = 0
)

# Examine the model's results
model_4
```

# Code snippet 11
```{r snippet-11, warning=FALSE, message=FALSE}
# Define the formula separately for clarity
form <- bf(
  analyser_2 | se(sd_analyser_2, sigma = TRUE) ~ 0 + Intercept + me(analyser_1, sd_analyser_1)
)

model_5 <- brm(
  formula = form
  ,data = df_example_4
  ,family = gaussian
  ,prior = c(
    prior(normal(0, 10), class = "b", coef = "Intercept")
    ,prior(normal(1, 0.5), class = "b", coef = "meanalyser_1sd_analyser_1")
    ,prior(exponential(1.7), class = "sigma")
  )
  ,seed = 1234
  ,iter = 3000
  ,refresh = 0
)

# Examine the model's results
model_5
```

# Figure 3
```{r fig-3, echo=FALSE, warning=FALSE, message=FALSE}
# Figure 3A
x_min_data <- min(df_example_4$analyser_1)
x_min <- 2.5
x_max_data <- max(df_example_4$analyser_1)
x_max <- 8.5

fig_3a <- ggplot(df_example_4, aes(x = analyser_1, y = analyser_2))+
  geom_errorbar(aes(ymin = analyser_2 - sd_analyser_2, ymax = analyser_2 + sd_analyser_2), alpha = 0.5, width = 0)+
  geom_errorbarh(aes(xmin = analyser_1 - sd_analyser_1, xmax = analyser_1 + sd_analyser_1), alpha = 0.5, width = 0)+
  geom_point(alpha = 0.5)+
  geom_abline(slope = 1, intercept = 0, colour = "red2", linetype = "dashed", alpha = 0.5)+
  theme_plot+
  xlab("Potassium, analyser 1 (mmol/L)")+
  ylab("Potassium, analyser 2 (mmol/L)")+
  scale_x_continuous(breaks = seq(x_min, x_max, 1), limits = c(x_min, x_max))+
  scale_y_continuous(breaks = seq(x_min, x_max, 1), limits = c(x_min, x_max))

# Figure 3B
fig_3b <- fig_3a+
  geom_segment(
    x = x_min_data
    ,xend = x_max_data
    ,y = mcr_model@glob.coef[1] + x_min_data * mcr_model@glob.coef[2]
    ,yend = mcr_model@glob.coef[1] + x_max_data * mcr_model@glob.coef[2]
    ,col = "blue2"
  )

# Figure 3C
fig_3c <- model_4 %>%
  spread_draws(b_Intercept, b_analyser_1, n = 100, seed = 1234) %>%
  mutate(
    x = x_min_data
    ,xend = x_max_data
    ,y = b_Intercept + b_analyser_1 * x
    ,yend = b_Intercept + b_analyser_1 * xend
  ) %>%
  ggplot(aes(x = analyser_1, y = analyser_2))+
    geom_abline(slope = 1, intercept = 0, colour = "red2", linetype = "dashed", alpha = 0.5)+
    geom_errorbar(
      data = df_example_4
      ,aes(ymin = analyser_2 - sd_analyser_2, ymax = analyser_2 + sd_analyser_2), alpha = 0.5, width = 0
    )+
    geom_errorbarh(
      data = df_example_4
      ,aes(xmin = analyser_1 - sd_analyser_1, xmax = analyser_1 + sd_analyser_1), alpha = 0.5, width = 0
    )+
    geom_point(data = df_example_4, alpha = 0.5)+
    geom_segment(aes(x = x, xend = xend, y = y, yend = yend), alpha = 0.05, colour = "blue2")+
    theme_plot+
    xlab("Potassium, analyser 1 (mmol/L)")+
    ylab("Potassium, analyser 2 (mmol/L)")+
    scale_x_continuous(breaks = seq(x_min, x_max, 1), limits = c(x_min, x_max))+
    scale_y_continuous(breaks = seq(x_min, x_max, 1), limits = c(x_min, x_max))

# Figure 3D
fig_3d <- model_5 %>%
  spread_draws(b_Intercept, bsp_meanalyser_1sd_analyser_1, n = 100, seed = 1234) %>%
  mutate(
    x = x_min_data
    ,xend = x_max_data
    ,y = b_Intercept + bsp_meanalyser_1sd_analyser_1 * x
    ,yend = b_Intercept + bsp_meanalyser_1sd_analyser_1 * xend
  ) %>%
  ggplot(aes(x = analyser_1, y = analyser_2))+
    geom_abline(slope = 1, intercept = 0, colour = "red2", linetype = "dashed", alpha = 0.5)+
    geom_errorbar(
      data = df_example_4
      ,aes(ymin = analyser_2 - sd_analyser_2, ymax = analyser_2 + sd_analyser_2), alpha = 0.5, width = 0
    )+
    geom_errorbarh(
      data = df_example_4
      ,aes(xmin = analyser_1 - sd_analyser_1, xmax = analyser_1 + sd_analyser_1), alpha = 0.5, width = 0
    )+
    geom_point(data = df_example_4, alpha = 0.5)+
    geom_segment(aes(x = x, xend = xend, y = y, yend = yend), alpha = 0.05, colour = "blue2")+
    theme_plot+
    xlab("Potassium, analyser 1 (mmol/L)")+
    ylab("Potassium, analyser 2 (mmol/L)")+
    scale_x_continuous(breaks = seq(x_min, x_max, 1), limits = c(x_min, x_max))+
    scale_y_continuous(breaks = seq(x_min, x_max, 1), limits = c(x_min, x_max))

cowplot::plot_grid(fig_3a, fig_3b, fig_3c, fig_3d, align = "hv", axis = "lb", labels = c("A", "B", "C", "D"))
``` 

# Code snippet 12
```{r snippet-12, warning=FALSE, message=FALSE}
set.seed(1234)

# Generate some imprecision data for a fictional calcium assay's IQC
df_example_5 <- data.frame(
  day = factor(rep(1:5, each = 5))
  ,result = rep(rnorm(5, 1.8, 0.09), each = 5) + rnorm(25, 0, 0.05)
)

# Fit an ANOVA
VCA::anovaVCA(result ~ day, Data = df_example_5) 
```

# Code snippet 13
```{r snippet-13, warning=FALSE, message=FALSE}
# Fit the multilevel, varying effects model
model_6 <- brm(
  formula = result ~ 1 + (1|day)
  ,data = df_example_5
  ,family = gaussian
  ,prior = c(
    prior(normal(2.4, 1), class = "Intercept") # prior on alpha
    ,prior(exponential(6), class = "sd") # prior on sigma_day
    ,prior(exponential(12), class = "sigma") # prior on sigma
  )
  ,seed = 1234
  ,refresh = 0
  ,iter = 3000
  ,control = list(adapt_delta = 0.99)
)

# Examine the model's estimates
model_6

# Calculate the coefficient of variation posterior distribution
intermediate_var <- as.matrix(model_6)[,"sd_day__Intercept"]^2  
repeatability_var <- as.matrix(model_6)[,"sigma"]^2
total_sd <- sqrt(intermediate_var + repeatability_var) 
cv_posterior <- total_sd / as.matrix(model_6)[,"b_Intercept"] * 100

# Calculate P(hypothesis|data) that the CV is > 5%
sum(cv_posterior > 6) / length(cv_posterior)
```


# Code snippet 14
```{r code-snippet-14, warning=FALSE, message=FALSE}
set.seed(1234)

# Simulate some insulin stability data for 10 patient samples measured over 4 days
df_example_6 <- data.frame(patient = factor(1:10)) %>%
  group_by(patient) %>%
  mutate(
    day0 = log(rnorm(1, 10, 2.5))
    ,day1 = day0 + rnorm(1, log(0.5), 0.1)
    ,day2 = day1 + rnorm(1, log(0.5), 0.1)
    ,day3 = day2 + rnorm(1, log(0.5), 0.1)
  ) %>%
  pivot_longer(
    cols = -patient
    ,values_to = "log_result"
    ,names_to = "day"
    ,names_prefix = "day"
  ) %>%
  mutate(day = as.numeric(day), result = exp(log_result))

# Fit a multilevel model to the data
model_7 <- brm(
  formula = log_result ~ 1 + day + (1|patient)
  ,data = df_example_6
  ,family = gaussian
  ,prior = c(
    prior(normal(1.2, 2.3), class = "Intercept") # prior on alpha
    ,prior(normal(0, 5), class = "b") # prior on beta
    ,prior(exponential(0.7), class = "sd") # prior on sigma_patient
    ,prior(exponential(1.3), class = "sigma") # prior on sigma
  )
  ,seed = 1234
  ,refresh = 0
  ,control = list(adapt_delta = 0.99)
)

# Examine the model's estimates
model_7

# Back-transform the slope (beta) estimate to a percentage change
quantile((exp(as.matrix(model_7)[,"b_day"]) - 1) * 100, probs = c(0.025, 0.5, 0.975))
```

# Figure 4
```{r fig-4a, echo=FALSE, warning=FALSE, message=FALSE}
# Figure 4A
fig_4a <- ggplot(df_example_5, aes(x = day, y = result))+
  geom_point(alpha = 0.5, size = 2)+
  theme_plot+
  xlab("Day")+
  ylab("Total calcium (mmol/L)")

# Figure 4B
df_densities <- data.frame(value = cv_posterior) %>%
  summarise(
    density_x = density(value, adjust = 1.5)$x
    ,density_y = density(value, adjust = 1.5)$y
    ,max_density = max(density_y, na.rm = TRUE)
    ,density_y_norm = density_y / max_density
  ) %>%
  rowwise() %>%
  mutate(density_x_hyp = if_else(density_x > 6, true = density_x, false = NULL))  

fig_4b <- ggplot(df_densities, aes(x = density_x, y = density_y_norm))+
  geom_line()+
  geom_area(aes(x = density_x_hyp), fill = "red2", alpha = 0.25, colour = "black")+
  geom_vline(xintercept = 6, colour = "red2", size = 1)+
  theme_plot+
  xlab("CV (%)")+
  ylab("Density (A.U.)")+
  expand_limits(x = 0)

# Figure 4C
x_min <- 0
x_max <- 3

# Figure 4C
fig_4c <- ggplot(df_example_6, aes(x = day, y = result))+
  geom_point(alpha = 0.5, size = 2)+
  geom_line(aes(group = patient), alpha = 0.5)+
  theme_plot+
  theme(legend.position = "none")+
  expand_limits(y = 0)+
  xlab("Time (day)")+
  ylab("Insulin (mU/L)")

# Figure 4D
fig_4d <- model_7 %>%
  spread_draws(b_Intercept, b_day, n = 100, seed = 1234) %>%
  mutate(
    x = x_min
    ,xend = x_max
    ,y = b_Intercept + b_day * x
    ,yend = b_Intercept + b_day * xend
  ) %>%
  ggplot(aes(x = day, y = log_result))+
    geom_point(data = df_example_6, alpha = 0.5)+
    geom_line(data = df_example_6, alpha = 0.1, aes(group = patient))+
    geom_segment(aes(x = x, xend = xend, y = y, yend = yend), alpha = 0.1, colour = "blue2")+
    theme_plot+
    xlab("Time (day)")+
    ylab("Log(insulin, mU/L)")

cowplot::plot_grid(fig_4a, fig_4b, fig_4c, fig_4d, align = "hv", axis = "lb", labels = c("A", "B", "C", "D"))
```
